import { useEffect, useMemo, useState } from 'react'
import { Link } from 'react-router-dom'
import AppHeader from '../components/AppHeader'
import { useAuth } from '../context/AuthContext'
import { supabase } from '../supabaseClient'

const money=n=>new Intl.NumberFormat('id-ID',{style:'currency',currency:'IDR',maximumFractionDigits:0}).format(Number(n||0))
const plans=[{id:'commission',name:'VIP Bagi Hasil',price:'5%',desc:'Komisi 5% dari setiap pesanan selama VIP aktif.',icon:'📈'},{id:'daily',name:'VIP Harian',price:'Rp15.000/hari',desc:'Tarif tetap per hari tanpa komisi pesanan.',icon:'⭐'}]

export default function Merchant(){
 const {user}=useAuth(); const [merchant,setMerchant]=useState(null); const [vip,setVip]=useState(null); const [products,setProducts]=useState([]); const [orders,setOrders]=useState([]); const [plan,setPlan]=useState('commission'); const [form,setForm]=useState({nama_merchant:'',kategori:'',alamat:'',deskripsi:''}); const [product,setProduct]=useState({nama:'',harga:'',deskripsi:''}); const [msg,setMsg]=useState(''); const [loading,setLoading]=useState(true);
 const load=async()=>{ if(!user)return; setLoading(true); const {data:m}=await supabase.from('merchant_profiles').select('*').eq('owner_id',user.id).maybeSingle(); setMerchant(m); if(m){setForm(m); const [{data:v},{data:p},{data:o}]=await Promise.all([supabase.from('merchant_vip').select('*').eq('merchant_id',m.id).order('created_at',{ascending:false}).limit(1).maybeSingle(),supabase.from('merchant_products').select('*').eq('merchant_id',m.id).order('created_at',{ascending:false}),supabase.from('merchant_orders').select('*').eq('merchant_id',m.id).order('created_at',{ascending:false}).limit(50)]); setVip(v); setProducts(p||[]); setOrders(o||[])} setLoading(false)};
 useEffect(()=>{load()},[user])
 const saveMerchant=async(e)=>{e.preventDefault();setMsg('');let m=merchant; const payload={...form,owner_id:user.id}; if(m){const {data,error}=await supabase.from('merchant_profiles').update({...form,updated_at:new Date().toISOString()}).eq('id',m.id).select().single(); if(error){setMsg(error.message);return}m=data}else{const {data,error}=await supabase.from('merchant_profiles').insert(payload).select().single();if(error){setMsg(error.message);return}m=data;setMerchant(data)} setMsg('Profil merchant tersimpan.')}
 const submitVip=async()=>{if(!merchant){setMsg('Simpan profil merchant terlebih dahulu.');return} const {error}=await supabase.from('merchant_vip').insert({merchant_id:merchant.id,merchant_name:merchant.nama_merchant,plan,status:'pending'});setMsg(error?'Pengajuan VIP gagal. Silakan coba lagi.':'Pengajuan VIP terkirim. Admin akan memverifikasi.');if(!error)load()}
 const addProduct=async(e)=>{e.preventDefault();if(!merchant){setMsg('Simpan profil merchant terlebih dahulu.');return} const {error}=await supabase.from('merchant_products').insert({merchant_id:merchant.id,nama:product.nama,harga:Number(product.harga),deskripsi:product.deskripsi}); if(error)setMsg('Produk belum dapat disimpan. Jalankan schema terbaru di Supabase.');else{setProduct({nama:'',harga:'',deskripsi:''});setMsg('Produk berhasil dikirim, menunggu verifikasi admin sebelum tampil ke pembeli.');load()}}
 const updateOrder=async(id,status)=>{const {error}=await supabase.from('merchant_orders').update({status,updated_at:new Date().toISOString()}).eq('id',id).eq('merchant_id',merchant.id);setMsg(error?'Status pesanan gagal diubah.':'Status pesanan diperbarui.');if(!error)load()}
 const activeVip=vip&&['active','approved'].includes(vip.status); const omzet=useMemo(()=>orders.filter(o=>['paid','processing','ready','completed','selesai'].includes(String(o.status).toLowerCase())).reduce((a,o)=>a+Number(o.total_amount||0),0),[orders]);
 if(loading)return <div className="min-h-screen bg-slate-50"><AppHeader title="Merchant Center" backTo="/"/><main className="max-w-3xl mx-auto p-6"><div className="card p-8 text-center text-sm text-gray-400">Memuat Merchant Center…</div></main></div>
 return <div className="min-h-screen bg-slate-50 page-with-bottom-nav"><AppHeader title="Merchant Center" backTo="/"/><main className="max-w-3xl mx-auto p-4 md:p-6 space-y-4">
  <section className="rounded-3xl bg-gradient-to-br from-brand-950 via-brand-800 to-brand-600 text-white p-6 shadow-xl"><div className="flex items-start justify-between gap-4"><div><span className="inline-flex px-2.5 py-1 rounded-full bg-white/15 text-[11px] font-bold">⭐ MERCHANT CENTER</span><h1 className="text-2xl font-black mt-3">Kelola usaha dari satu tempat.</h1><p className="text-xs text-brand-100 mt-2">Profil, produk, pesanan, VIP, dan performa merchant.</p></div>{activeVip&&<span className="px-3 py-1.5 rounded-full bg-white text-brand-800 text-xs font-black">VIP AKTIF</span>}</div></section>
  <section className="grid grid-cols-3 gap-3"><div className="card p-4"><p className="text-[10px] font-bold text-gray-400 uppercase">Produk</p><b className="text-2xl text-brand-700">{products.length}</b></div><div className="card p-4"><p className="text-[10px] font-bold text-gray-400 uppercase">Pesanan</p><b className="text-2xl text-brand-700">{orders.length}</b></div><div className="card p-4"><p className="text-[10px] font-bold text-gray-400 uppercase">Omzet</p><b className="text-sm text-brand-700">{money(omzet)}</b></div></section>
  <form onSubmit={saveMerchant} className="card p-5 space-y-4"><div><h2 className="font-extrabold">Profil usaha</h2><p className="text-xs text-gray-500 mt-1">Profil yang lengkap lebih mudah dipercaya warga.</p></div>{[['nama_merchant','Nama usaha'],['kategori','Kategori'],['alamat','Alamat']].map(([k,l])=><div key={k}><label className="field-label">{l}</label><input required value={form[k]||''} onChange={e=>setForm({...form,[k]:e.target.value})} className="input-field"/></div>)}<div><label className="field-label">Deskripsi</label><textarea required value={form.deskripsi||''} onChange={e=>setForm({...form,deskripsi:e.target.value})} className="input-field min-h-24"/></div><button className="btn-primary">Simpan profil</button></form>
  <section className="card p-5"><div className="flex justify-between items-start gap-3"><div><h2 className="font-extrabold">⭐ VIP Merchant</h2><p className="text-xs text-gray-500 mt-1">Pilih skema prioritas yang sesuai bisnis.</p></div>{vip&&<span className="badge-brand">{vip.status}</span>}</div><div className="grid md:grid-cols-2 gap-3 mt-4">{plans.map(p=><button key={p.id} type="button" onClick={()=>setPlan(p.id)} className={`text-left rounded-2xl border-2 p-4 ${plan===p.id?'border-brand-500 bg-brand-50':'border-gray-100 bg-white'}`}><b>{p.icon} {p.name}</b><p className="text-xl font-black text-brand-700 mt-1">{p.price}</p><p className="text-xs text-gray-500 mt-1">{p.desc}</p></button>)}</div><button type="button" onClick={submitVip} disabled={vip?.status==='pending'||activeVip} className="btn-primary w-full mt-4">{activeVip?'VIP sedang aktif':vip?.status==='pending'?'Menunggu verifikasi':'Ajukan paket VIP'}</button></section>
  <section className="card p-5"><h2 className="font-extrabold">Produk</h2><p className="text-xs text-gray-500 mt-1">Tambahkan produk yang bisa dipesan warga.</p><form onSubmit={addProduct} className="grid gap-2 mt-4"><input required value={product.nama} onChange={e=>setProduct({...product,nama:e.target.value})} className="input-field" placeholder="Nama produk"/><input required type="number" min="0" value={product.harga} onChange={e=>setProduct({...product,harga:e.target.value})} className="input-field" placeholder="Harga"/><input value={product.deskripsi} onChange={e=>setProduct({...product,deskripsi:e.target.value})} className="input-field" placeholder="Deskripsi singkat"/><button className="btn-secondary">+ Tambah produk</button></form><div className="mt-4 space-y-2">{products.map(p=><div key={p.id} className="rounded-xl border border-gray-100 p-3 flex justify-between gap-3"><div><b className="text-sm">{p.nama}</b><p className="text-xs text-gray-500">{money(p.harga)}</p></div><span className="badge-success">{p.status}</span></div>)}</div></section>
  <section className="card p-5"><h2 className="font-extrabold">Pesanan terbaru</h2><div className="mt-4 space-y-2">{orders.length===0?<div className="py-6 text-center text-sm text-gray-400">Belum ada pesanan masuk.</div>:orders.map(o=><div key={o.id} className="rounded-xl border border-gray-100 p-3"><div className="flex justify-between gap-3"><div><b className="text-sm">#{String(o.id).slice(0,8)}</b><p className="text-xs text-gray-500 mt-1">{money(o.total_amount)} · {o.status}</p></div><select value={o.status} onChange={e=>updateOrder(o.id,e.target.value)} className="input-field !w-auto !py-2 text-xs"><option value="pending">Menunggu</option><option value="accepted">Diterima</option><option value="processing">Diproses</option><option value="ready">Siap</option><option value="completed">Selesai</option><option value="cancelled">Dibatalkan</option></select></div></div>)}</div></section>
  {msg&&<div className="rounded-2xl bg-brand-50 border border-brand-100 text-brand-800 p-4 text-xs font-semibold">{msg}</div>}
  {merchant?.id&&<Link to={`/merchant/${merchant.id}`} className="btn-ghost block text-center">Lihat halaman merchant publik →</Link>}
 </main></div>
}
